import { useUnsavedChanges } from '../components/useUnsavedChanges';
import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, RefreshCw } from 'lucide-react';
import { useAuth } from '../../app/providers/AuthProvider';
import { AdminBadge, AdminCard, AdminEmptyState, AdminModal, PageHeader } from '../components/AdminPrimitives';
import { billingService } from './billing.service';
import { blankService, serviceTemplates, todayDate, dueState, costLabel, dateLabel, billingTotals } from './billingModel';

export default function BillingPage() {
  const { user } = useAuth();
  const manage = user?.role === 'super_admin';
  const [services, setServices] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [search, setSearch] = useState(''), [filter, setFilter] = useState('active');
  const [editing, setEditing] = useState(null), [form, setForm] = useState(blankService), [saving, setSaving] = useState(false), [formError, setFormError] = useState('');
  const [payment, setPayment] = useState(null), [paymentForm, setPaymentForm] = useState({}), [history, setHistory] = useState(null), [historyError, setHistoryError] = useState('');
  const serviceDirty = Boolean(editing) && JSON.stringify(Object.fromEntries(Object.keys(blankService).map(key => [key, form[key] || '']))) !== JSON.stringify(Object.fromEntries(Object.keys(blankService).map(key => [key, editing?.id ? key === 'amount' ? editing.amount === null ? '' : String(editing.amount) : editing[key] || '' : blankService[key] || ''])));
  const serviceDraft = useUnsavedChanges({ key: `${user?.id}:billing:${editing?.id || 'new'}`, dirty: serviceDirty, draft: form, restore: setForm, ready: Boolean(editing) });
  const paymentDirty = Boolean(payment) && (Boolean(formError) || Boolean(paymentForm.reference || paymentForm.next_due_date) || paymentForm.paid_on !== todayDate() || paymentForm.amount !== (payment.amount === null ? '' : String(payment.amount)));
  const paymentDraft = useUnsavedChanges({ key: `${user?.id}:billing-payment:${payment?.id || 'new'}`, dirty: paymentDirty, draft: paymentForm, restore: setPaymentForm, ready: Boolean(payment) });
  const load = useCallback(async () => { setLoading(true); setError(''); try { setServices((await billingService.list()).results); } catch (e) { setError(e.message || 'Unable to load billing.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const openService = service => { setEditing(service || {}); setForm(service ? { ...service, amount: service.amount === null ? '' : String(service.amount), next_due_date: service.next_due_date || '' } : { ...blankService }); setFormError(''); };
  const field = (name, value) => setForm(previous => ({ ...previous, [name]: value }));
  const save = async event => { event.preventDefault(); setSaving(true); setFormError(''); const body = Object.fromEntries(Object.keys(blankService).map(key => [key, form[key]])); body.amount = form.amount === '' ? null : form.amount; body.next_due_date = form.next_due_date || null;
    try { const result = editing.id ? await billingService.update(editing.id, { ...body, expected_updated_at: editing.updated_at }) : await billingService.create(body); setServices(previous => [...previous.filter(s => s.id !== result.id), result]); serviceDraft.discard(); setEditing(null); } catch (e) { setFormError(e.message || 'Unable to save service.'); } finally { setSaving(false); } };
  const openPayment = service => { setPayment(service); setFormError(''); setPaymentForm({ amount: service.amount === null ? '' : String(service.amount), currency: service.currency, paid_on: todayDate(), next_due_date: '', reference: '', expected_updated_at: service.updated_at, idempotency_key: crypto.randomUUID() }); };
  const record = async event => { event.preventDefault(); setSaving(true); setFormError(''); try { const result = await billingService.recordPayment(payment.id, { ...paymentForm, next_due_date: paymentForm.next_due_date || null }); setServices(previous => previous.map(s => s.id === result.service.id ? result.service : s)); paymentDraft.discard(); setPayment(null); } catch (e) { setFormError(`${e.message || 'Unable to record payment.'}${!e.status || e.status >= 500 ? ' Outcome may be unknown. Check payment history before starting another record; retrying this unchanged form uses the same submission key.' : ''}`); } finally { setSaving(false); } };
  const showHistory = async service => { setHistory({ service, results: null }); setHistoryError(''); try { const result = await billingService.payments(service.id); setHistory(previous => previous?.service.id === service.id ? { service, results: result.results } : previous); } catch (e) { setHistoryError(e.message || 'Unable to load payment history.'); } };
  const filtered = services.filter(s => (filter === 'all' || (filter === 'active' ? s.active : !s.active)) && `${s.name} ${s.owner} ${s.category}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => (a.next_due_date || '9999').localeCompare(b.next_due_date || '9999'));
  const overdue = services.filter(s => dueState(s).label === 'Overdue').length;
  const totals = billingTotals(services);
  return <div className="admin-page">
    <PageHeader title="Billing" help="Track external service bills and renewals. Amounts are manually entered estimates; recording payment does not charge a card or contact a provider. Due dates use your local calendar date." action={<>{manage && <button className="admin-primary-button" type="button" onClick={() => openService(null)}><Plus size={16} />Add service</button>}<Link className="admin-secondary-button" to="/admin/settings">Settings</Link></>} />
    <div className="operations-summary"><AdminCard><span>Active services</span><strong>{loading || error ? '—' : services.filter(s => s.active).length}</strong></AdminCard><AdminCard><span>Overdue</span><strong>{loading || error ? '—' : overdue}</strong></AdminCard><AdminCard><span>Recorded costs due within 30 days, including overdue</span><strong>{loading || error ? '—' : Object.entries(totals).map(([currency, minor]) => costLabel({ currency, amount: minor / 100 })).join(' · ') || 'No recorded costs'}</strong></AdminCard></div>
    <AdminCard><div className="admin-toolbar"><label className="operations-search">Search services<input aria-label="Search services" value={search} onChange={e => setSearch(e.target.value)} placeholder="Service or owner" /></label><label>Status<select value={filter} onChange={e => setFilter(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All services</option></select></label><button className="admin-secondary-button" type="button" onClick={load} disabled={loading}><RefreshCw size={15} />Refresh</button></div>
      {error && <p className="operations-message" role="alert">{error}</p>}
      {loading ? <div className="admin-state" role="status">Loading services…</div> : !error && !filtered.length ? <AdminEmptyState title="No services found" description={services.length ? 'Try a different search or status.' : 'Add actual service costs and renewal dates to start tracking.'} action={manage && !services.length ? <button className="admin-secondary-button" type="button" onClick={() => openService(null)}>Add your first service</button> : null} /> : !error && <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Service</th><th>Cost / cycle</th><th>Due date</th><th>Status</th><th>Owner</th><th>Actions</th></tr></thead><tbody>{filtered.map(s => { const due = dueState(s); return <tr key={s.id}><td>{s.name}<small className="operations-detail">{s.category}</small></td><td>{costLabel(s)}<small className="operations-detail">{s.cycle.replaceAll('_', ' ')}</small></td><td>{dateLabel(s.next_due_date)}</td><td><AdminBadge tone={due.tone}>{due.label}</AdminBadge></td><td>{s.owner || 'Unassigned'}</td><td><div className="operations-actions">{manage && <button className="admin-secondary-button" type="button" onClick={() => openService(s)}>Edit</button>}{manage && s.active && <button className="admin-secondary-button" type="button" onClick={() => openPayment(s)}>Record payment</button>}<button className="admin-secondary-button" type="button" onClick={() => showHistory(s)}>History</button>{s.portal_url && <a href={s.portal_url} target="_blank" rel="noreferrer" className="admin-secondary-button">Provider portal<span className="sr-only"> (new tab)</span></a>}</div></td></tr>; })}</tbody></table></div>}
    </AdminCard>
    <AdminModal guardChanges={false} open={Boolean(editing)} title={editing?.id ? 'Edit service' : 'Add service'} onClose={() => { if (!saving && (!serviceDirty || window.confirm('Discard unsaved service changes?'))) { serviceDraft.discard(); setEditing(null); } }}>
      <form className="operations-form" onSubmit={save}>{serviceDraft.restored && <p role="status">Unsaved service draft restored. Review before saving.</p>}
        {!editing?.id && <label>Quick add<select defaultValue="" onChange={e => { const template = serviceTemplates.find(t => t.name === e.target.value); if (template) setForm(previous => ({ ...previous, ...template })); }}><option value="">Choose a service or enter your own</option>{serviceTemplates.map(t => <option key={t.name}>{t.name}</option>)}</select></label>}
        <label>Service name<input required maxLength={100} value={form.name} onChange={e => field('name', e.target.value)} /></label>
        <div className="operations-form-grid"><label>Category<select value={form.category} onChange={e => field('category', e.target.value)}>{['hosting', 'email', 'domain', 'workspace', 'other'].map(v => <option key={v}>{v}</option>)}</select></label><label>Owner<input maxLength={120} value={form.owner} onChange={e => field('owner', e.target.value)} /></label><label>Estimated cost<input type="number" min="0" max="999999999.99" step="0.01" value={form.amount} onChange={e => field('amount', e.target.value)} /></label><label>Currency<select value={form.currency} onChange={e => field('currency', e.target.value)}>{['USD', 'KES', 'EUR', 'GBP'].map(v => <option key={v}>{v}</option>)}</select></label><label>Billing cycle<select value={form.cycle} onChange={e => field('cycle', e.target.value)}>{['monthly', 'quarterly', 'annual', 'one_time', 'usage_based'].map(v => <option key={v} value={v}>{v.replaceAll('_', ' ')}</option>)}</select></label><label>Next due date<input type="date" value={form.next_due_date} onChange={e => field('next_due_date', e.target.value)} /></label></div>
        <label>Provider portal URL<input type="url" placeholder="https://" maxLength={1000} value={form.portal_url} onChange={e => field('portal_url', e.target.value)} /></label><label>Notes<textarea maxLength={2000} value={form.notes} onChange={e => field('notes', e.target.value)} /></label><label className="operations-checkbox"><input type="checkbox" checked={form.active} onChange={e => field('active', e.target.checked)} />Active service</label>
        <p className="operations-detail">Leave unknown costs or dates empty. Do not store passwords, API keys or card details.</p>{formError && <p role="alert">{formError}</p>}<div className="operations-actions"><button className="admin-secondary-button" type="button" disabled={saving} onClick={() => { if (!serviceDirty || window.confirm('Discard unsaved service changes?')) { serviceDraft.discard(); setEditing(null); } }}>Cancel</button><button className="admin-primary-button" disabled={saving}>{saving ? 'Saving…' : 'Save service'}</button></div>
      </form>
    </AdminModal>
    <AdminModal guardChanges={false} open={Boolean(payment)} title={`Record payment · ${payment?.name || ''}`} description="Record a payment already made outside LTC. This does not send money. Enter the next deadline explicitly; leave it empty if there is no further bill." onClose={() => { if (!saving && (!paymentDirty || window.confirm('Close this payment draft? Check History before starting another record if the outcome was unknown.'))) setPayment(null); }}><form className="operations-form" onSubmit={record}>{paymentDraft.restored && <p role="status">Unsaved payment draft restored, including its submission key.</p>}<label>Amount paid ({paymentForm.currency})<input required type="number" min="0" max="999999999.99" step="0.01" value={paymentForm.amount || ''} onChange={e => setPaymentForm(p => ({ ...p, amount: e.target.value }))} /></label><label>Payment date<input required type="date" value={paymentForm.paid_on || ''} onChange={e => setPaymentForm(p => ({ ...p, paid_on: e.target.value }))} /></label><label>Next due date<input type="date" value={paymentForm.next_due_date || ''} onChange={e => setPaymentForm(p => ({ ...p, next_due_date: e.target.value }))} /></label><label>Receipt or invoice reference<input maxLength={120} value={paymentForm.reference || ''} onChange={e => setPaymentForm(p => ({ ...p, reference: e.target.value }))} /></label>{formError && <p role="alert">{formError}</p>}<button className="admin-primary-button" disabled={saving}>{saving ? 'Recording…' : 'Record payment'}</button></form></AdminModal>
    <AdminModal open={Boolean(history)} title={`Payment history · ${history?.service.name || ''}`} onClose={() => setHistory(null)}>{historyError ? <p role="alert">{historyError}</p> : history?.results === null ? <p role="status">Loading history…</p> : !history?.results?.length ? <p>No payments recorded.</p> : <ul className="operations-history">{history.results.map(p => <li key={p.id}><span>{dateLabel(p.paid_on)} · {costLabel(p)}</span><small>{p.reference || 'No reference'}</small></li>)}</ul>}</AdminModal>
  </div>;
}
