import ListPagination from '../components/ListPagination';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Search } from 'lucide-react';
import { AdminCard, AdminEmptyState, AdminModal, AdminBadge, PageHeader } from '../components/AdminPrimitives';
import { adminDataProvider } from '../data/adminDataProvider';
import { useAuth } from '../../app/providers/AuthProvider';

export default function MentorsPage() {
  const loadVersion = useRef(0);
  const [page, setPage] = useState(0);
  const { can } = useAuth();
  const [mentors, setMentors] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(() => { const version = ++loadVersion.current; setLoading(true); setError(''); adminDataProvider.listMentors({ limit: 50, offset: page * 50, search, status: { new: 'pending', 'under-review': 'under_review' }[status] || status }).then((items) => { if (version === loadVersion.current) setMentors(items); }).catch((err) => { if (version === loadVersion.current) setError(err.message); }).finally(() => { if (version === loadVersion.current) setLoading(false); }); }, [page, search, status]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => mentors.filter((mentor) => `${mentor.name} ${mentor.email} ${mentor.background}`.toLowerCase().includes(search.toLowerCase()) && (status === 'all' || mentor.status.toLowerCase().replace(' ', '-') === status)), [mentors, search, status]);
  const setMentorStatus = async (nextStatus) => { const updated = await adminDataProvider.updateMentorStatus(selected.id, nextStatus); setMentors((items) => items.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); };
  return <div className="admin-page"><PageHeader title="Mentor Requests" help="Review expressions of interest and update their existing review status." /><AdminCard><div className="admin-card__body"><div className="admin-toolbar"><div className="admin-search-wrap"><Search size={15} aria-hidden="true" /><input className="admin-search" aria-label="Search mentor requests" placeholder="Search name, email or background" value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} /></div><select className="admin-select" aria-label="Filter mentor requests" value={status} onChange={(event) => { setStatus(event.target.value); setPage(0); }}><option value="all">All statuses</option><option value="new">New</option><option value="under-review">Under review</option><option value="approved">Approved</option><option value="declined">Declined</option></select><span className="admin-count">{filtered.length} requests</span></div>{loading && !mentors.length ? <div className="admin-state" role="status">Loading mentor requests…</div> : error ? <AdminEmptyState title="We couldn't load mentor requests" description={error} action={<button className="admin-secondary-button" type="button" onClick={load}>Try again</button>} /> : filtered.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Mentor</th><th>Background</th><th>Interest</th><th>Submitted</th><th>Status</th><th /></tr></thead><tbody>{filtered.map((mentor) => <tr key={mentor.id}><td><div className="admin-table__identity"><span className="admin-avatar">{mentor.name.split(' ').map((part) => part[0]).join('')}</span><div><div className="admin-identity-name">{mentor.name}</div><div className="admin-identity-sub">{mentor.email}</div></div></div></td><td>{mentor.background}</td><td>{mentor.helpOptions[0]}</td><td>{mentor.submitted}</td><td><AdminBadge tone={mentor.status === 'New' ? 'warning' : mentor.status === 'Approved' ? 'success' : ''}>{mentor.status}</AdminBadge></td><td><button className="admin-table-action" type="button" onClick={() => setSelected(mentor)}>Review</button></td></tr>)}</tbody></table></div> : <AdminEmptyState title="No mentor requests found" description="New mentorship applications will appear here." />}</div></AdminCard><ListPagination page={page} setPage={setPage} count={mentors.length} loading={loading} label="mentor requests" />
    <AdminModal open={Boolean(selected)} title={selected?.name || 'Mentor request'} description={selected?.email} onClose={() => setSelected(null)} actions={<button className="admin-secondary-button" type="button" onClick={() => setSelected(null)}>Close</button>}>{selected && <><div className="admin-form-field"><label>Professional background</label><p className="admin-modal-copy">{selected.background}</p></div><div className="admin-form-field"><label>Ways they would like to help</label><p className="admin-modal-copy">{selected.helpOptions.join(', ')}</p></div><div className="admin-form-field"><label>Message</label><p className="admin-modal-copy">{selected.message}</p></div><div className="admin-form-field"><label htmlFor="mentor-status">Status</label><select id="mentor-status" value={selected.status} disabled={!can('mentors.update')} onChange={(event) => setMentorStatus(event.target.value)}><option>New</option><option>Under review</option><option>Approved</option><option>Declined</option></select></div></>}</AdminModal>
  </div>;
}
