export const endpoints = {
  auth: {
    login: '/api/auth/login',
    refresh: '/api/auth/refresh',
    me: '/api/auth/me',
    forgotPassword: '/api/auth/forgot-password',
    setPassword: '/api/auth/set-password',
    changePassword: '/api/auth/change-password',
  },
  stories: '/api/stories',
  unsubscribe: (token) => `/api/unsubscribe/${encodeURIComponent(token)}/`,
  adminStories: {
    list: '/api/admin/stories',
    detail: (id) => `/api/admin/stories/${id}`,
  },
  adminNewsletters: {
    list: '/api/admin/newsletters/',
    detail: (id) => `/api/admin/newsletters/${id}/`,
    banner: (id) => `/api/admin/newsletters/${id}/banner/`,
    attachments: (id) => `/api/admin/newsletters/${id}/attachments/`,
    attachment: (id, attachmentId) => `/api/admin/newsletters/${id}/attachments/${attachmentId}/`,
    preview: (id) => `/api/admin/newsletters/${id}/preview/`,
    send: (id) => `/api/admin/newsletters/${id}/send/`,
    status: (id) => `/api/admin/newsletters/${id}/status/`,
  },
  subscriberCount: '/api/admin/subscribers/count/',
  adminTeamProfiles: {
    list: '/api/admin/team-profiles',
    detail: (id) => `/api/admin/team-profiles/${id}`,
    reorder: '/api/admin/team-profiles/reorder',
    action: (id, name) => `/api/admin/team-profiles/${id}/${name}`,
    mine: '/api/admin/my-team-profile',
  },
  adminUsers: {
    list: '/api/admin/users',
    detail: (id) => `/api/admin/users/${id}`,
    invitations: '/api/admin/users/invitations',
    resendInvitation: (id) => `/api/admin/users/${id}/invitation/resend`,
    revokeInvitation: (id) => `/api/admin/users/${id}/invitation/revoke`,
    permissions: (id) => `/api/admin/users/${id}/permissions`,
    resetPermissions: (id) => `/api/admin/users/${id}/permissions/reset`,
    role: (id) => `/api/admin/users/${id}/role`,
    status: (id) => `/api/admin/users/${id}/status`,
    disable: (id) => `/api/admin/users/${id}/disable`,
    enable: (id) => `/api/admin/users/${id}/enable`,
    regeneratePassword: (id) => `/api/admin/users/${id}/regenerate-password`,
    delete: (id) => `/api/admin/users/${id}`,
  },
  permissions: '/api/admin/permissions',
  rolePermissions: '/api/admin/role-permissions',
  rolePermissionDetail: (role) => `/api/admin/roles/${encodeURIComponent(role)}/permissions`,
  userAuthorizations: '/api/admin/user-authorizations',
  audit: {
    list: '/api/audit',
    summary: '/api/audit/summary',
    detail: (id) => `/api/audit/${id}`,
  },
  profileSubmissionLinks: {
    list: '/api/admin/profile-submission-links',
    create: '/api/admin/profile-submission-links',
    revoke: (id) => `/api/admin/profile-submission-links/${id}/revoke`,
    validate: (token) => `/api/profile-submission-links/${encodeURIComponent(token)}/validate`,
    submit: (token) => `/api/profile-submissions/${encodeURIComponent(token)}`,
    upload: (token, profileId) => `/api/profile-submissions/${encodeURIComponent(token)}/image?profile_id=${encodeURIComponent(profileId)}`,
  },
  subscribe: '/api/subscribe/',
  mentorApplications: '/api/mentors/applications/',
  adminMentorApplications: {
    list: '/api/admin/mentors/applications',
    detail: (id) => `/api/admin/mentors/applications/${id}`,
  },
  donations: {
    checkoutSession: '/api/donations/checkout-session/',
    session: (sessionId) => `/api/donations/session/${encodeURIComponent(sessionId)}/`,
    progress: '/api/donations/progress/',
    supporters: '/api/donations/supporters/',
    supporterPublication: (id) => `/api/donations/admin/session/${encodeURIComponent(id)}/supporter-publication/`,
    pledges: '/api/donations/pledges/',
    adminList: '/api/admin/donations',
    manual: '/api/admin/donations/manual',
    adminPledges: '/api/admin/donations/pledges',
    adminPledge: (id) => `/api/admin/donations/pledges/${encodeURIComponent(id)}`,
  },
  dashboard: '/api/admin/dashboard/',
};
