import { test } from 'node:test';
import assert from 'node:assert/strict';
import { processDelivery, type DeliveryStore } from '../src/jobs/delivery.js';
import { HttpError } from '../src/shared/errors.js';
import type { Row } from '../src/shared/data.js';
function store(recipient: Row = { subscriber_id: 'fixture', email: 'fixture@example.invalid', status: 'pending' }) { let claimed = false; let final = false; const r = { ...recipient }; const state = { r, reset: () => { claimed = false; }, done: () => final }; const adapter: DeliveryStore = { claim: async () => { if (claimed)
        return undefined; claimed = true; return { id: 'fixture-job', snapshot: {} }; }, recipients: async () => r.status === 'pending' ? [{ ...r }] : [], suppressed: async () => false, start: async () => { r.attempts = Number(r.attempts || 0) + 1; r.first_attempt_at ??= new Date().toISOString(); }, record: async (_id, _r, status, providerId) => { r.status = status; r.provider_id = providerId; }, renew: async () => { }, finish: async () => { final = true; return true; } }; return { ...state, adapter }; }
test('transient failure retains pending recipient for restart and stable idempotency', async () => { const s = store(); const keys: string[] = []; await assert.rejects(processDelivery('job', s.adapter, async (_j, _r, key) => { keys.push(key); throw new HttpError(503, 'outage'); })); assert.equal(s.r.status, 'pending'); assert.equal(s.done(), false); s.reset(); await processDelivery('job', s.adapter, async (_j, _r, key) => { keys.push(key); return 'provider-fixture'; }); assert.equal(keys[0], keys[1]); assert.equal(s.r.status, 'accepted'); assert.equal(s.done(), true); });
test('provider acceptance followed by DB failure retries same provider key', async () => { const s = store(); const keys: string[] = []; const record = s.adapter.record; let crash = true; s.adapter.record = async (...args) => { if (crash) {
    crash = false;
    throw new Error('DB unavailable');
} await record(...args); }; await assert.rejects(processDelivery('job', s.adapter, async (_j, _r, key) => { keys.push(key); return 'accepted'; })); s.reset(); await processDelivery('job', s.adapter, async (_j, _r, key) => { keys.push(key); return 'accepted'; }); assert.deepEqual(keys, ['ltc-job-fixture', 'ltc-job-fixture']); });
test('unsubscribed recipient is suppressed immediately before send', async () => { const s = store(); s.adapter.suppressed = async () => true; await processDelivery('job', s.adapter, async () => { throw new Error('must not send'); }); assert.equal(s.r.status, 'suppressed'); });
test('ambiguous attempt beyond provider dedupe window requires reconciliation', async () => { const s = store({ subscriber_id: 'fixture', status: 'pending', first_attempt_at: new Date(Date.now() - 25 * 3600000).toISOString() }); await processDelivery('job', s.adapter, async () => { throw new Error('must not resend'); }); assert.equal(s.r.status, 'unknown'); });
test('duplicate active claim cannot deliver concurrently', async () => { const s = store(); await s.adapter.claim('job', 'owner'); assert.equal(await processDelivery('job', s.adapter, async () => { throw new Error('must not send'); }), false); });
