-- =========================================================
-- LTC DATABASE - PHASE 3
-- Tables:
-- 1. application_users
-- 2. profile_submission_links
-- 3. team_profiles
-- =========================================================


-- Needed for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- =========================================================
-- 1. APPLICATION USERS
-- Admin users who can access the LTC admin dashboard.
-- Authentication itself is handled by Supabase Auth.
-- =========================================================

CREATE TABLE public.application_users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    auth_user_id UUID NOT NULL UNIQUE
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    name TEXT NOT NULL,

    email TEXT NOT NULL UNIQUE,

    role TEXT NOT NULL DEFAULT 'admin'
        CHECK (role IN ('super_admin', 'admin')),

    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'disabled')),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 2. PROFILE SUBMISSION LINKS
-- Links generated by admins for team members to submit
-- their public LTC profile.
-- =========================================================

CREATE TABLE public.profile_submission_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    token_hash TEXT NOT NULL UNIQUE,

    created_by UUID NOT NULL
        REFERENCES public.application_users(id)
        ON DELETE CASCADE,

    expires_at TIMESTAMPTZ NOT NULL,

    used_at TIMESTAMPTZ,

    revoked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- =========================================================
-- 3. TEAM PROFILES
-- Public-facing LTC team member profiles.
-- These users DO NOT need admin accounts.
-- =========================================================

CREATE TABLE public.team_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    submission_link_id UUID
        REFERENCES public.profile_submission_links(id)
        ON DELETE SET NULL,

    name TEXT NOT NULL,
    
    email TEXT ,

    role TEXT NOT NULL,

    department TEXT,

    quote TEXT,

    bio TEXT,

    image_path TEXT,

    status TEXT NOT NULL DEFAULT 'pending'
        CHECK (
            status IN (
                'pending',
                'published',
                'rejected',
                'changes_requested'
            )
        ),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Submission links are reusable, up to the service's advertised limit.
-- Locking the parent link serializes concurrent inserts for the same link.
CREATE INDEX team_profiles_submission_link_id_idx
ON public.team_profiles(submission_link_id);

CREATE OR REPLACE FUNCTION public.enforce_profile_submission_link_limit()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.submission_link_id IS NULL THEN
        RETURN NEW;
    END IF;

    PERFORM 1
    FROM public.profile_submission_links
    WHERE id = NEW.submission_link_id
    FOR UPDATE;

    IF (
        SELECT COUNT(*)
        FROM public.team_profiles
        WHERE submission_link_id = NEW.submission_link_id
          AND id IS DISTINCT FROM NEW.id
    ) >= 100 THEN
        RAISE EXCEPTION 'profile submission link has reached its 100-profile limit'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER enforce_profile_submission_link_limit
BEFORE INSERT OR UPDATE OF submission_link_id ON public.team_profiles
FOR EACH ROW
EXECUTE FUNCTION public.enforce_profile_submission_link_limit();


-- =========================================================
-- AUTOMATIC updated_at
-- =========================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER update_application_users_updated_at
BEFORE UPDATE ON public.application_users
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


CREATE TRIGGER update_team_profiles_updated_at
BEFORE UPDATE ON public.team_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();


-- =========================================================
-- ENABLE ROW LEVEL SECURITY
-- We will define the actual policies during authentication/
-- security implementation.
-- =========================================================

ALTER TABLE public.application_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_submission_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_profiles ENABLE ROW LEVEL SECURITY;
