import { useUnsavedChanges } from '../components/useUnsavedChanges';
import { analyticsService } from '../dashboard/analytics.service';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../app/providers/AuthProvider';
import { AdminCard, PageHeader } from '../components/AdminPrimitives';
import { operationsSettingsService } from '../billing/billing.service';

export default function SettingsPage() {
  const { user, can } = useAuth();
  const [analytics, setAnalytics] = useState({ loading: true });
  useEffect(() => { let active = true; analyticsService.status().then(data => { if (active) setAnalytics({ data }); }).catch(e => { if (active) setAnalytics({ error: e.message || 'Unable to verify reporting configuration.' }); }); return () => { active = false; }; }, []);
  const manage = user?.role === 'super_admin';
  const [savedSettings, setSavedSettings] = useState(null);
  const [settings, setSettings] = useState({ analytics_provider: 'none', analytics_dashboard_url: '' });
  const [ready, setReady] = useState(false), [attempt, setAttempt] = useState(0);
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [error, setError] = useState(''), [status, setStatus] = useState('');
  useEffect(() => { let active = true; setLoading(true); setError(''); operationsSettingsService.get().then(result => { if (active) { setSettings(result); setSavedSettings(result); setReady(true); } }).catch(e => { if (active) setError(e.message || 'Unable to load settings.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [attempt]);
  const settingsDraft = useUnsavedChanges({ key: `${user?.id}:operations-settings`, dirty: ready && JSON.stringify(settings) !== JSON.stringify(savedSettings), draft: settings, restore: setSettings, ready });
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); setStatus(''); try { const result = await operationsSettingsService.save(settings); setSettings(result); setSavedSettings(result); settingsDraft.discard(); setStatus('Settings saved.'); } catch (e) { setError(e.message || 'Unable to save settings.'); } finally { setSaving(false); } };
  return <div className="admin-page"><PageHeader title="Settings" help="Configure operational shortcuts. Credentials and provider billing accounts remain outside this portal. Only super admins can change shared settings." />
    <div className="dashboard-operations-grid"><AdminCard><div className="admin-card__body"><h2>Service billing</h2><p className="operations-message">Track AWS, Resend, domain renewals, Google Workspace and other service deadlines in one shared register.</p>{(manage || can('donations.view')) ? <Link to="/admin/billing" className="admin-primary-button">Open billing</Link> : <p>Your account does not have billing access.</p>}</div></AdminCard>
      <AdminCard><div className="admin-card__body"><h2>Workspace</h2><p className="operations-message">Collapse or expand the desktop sidebar with the control in the top navbar. Your preference stays in this browser.</p><Link className="admin-secondary-button" to="/admin/profile">My profile</Link></div></AdminCard></div>
    <AdminCard><div className="admin-card__body"><h2>Website traffic</h2><p className="operations-message">GA4 aggregate reports appear on the Dashboard once reporting access is configured. Public collection is disabled until the tracking build is enabled and visitors grant analytics consent.</p><div className="operations-message">{analytics.loading ? <p role="status">Checking GA4 reporting…</p> : analytics.error ? <p role="alert">{analytics.error}</p> : <p>Reporting: {analytics.data.status === 'configured' ? 'Configured · access will be verified when loading reports' : analytics.data.status === 'configuration_incomplete' ? 'Setup incomplete' : 'Not configured'}</p>}<p>Public tracker: {import.meta.env.VITE_GA4_ENABLED === 'true' ? 'Build enabled · visitor consent required' : 'Collection disabled in this build'}</p></div><p className="operations-detail">Reporting credentials are configured on the backend and are never entered here. No analytics-consent notice has been added to the public website.</p><details className="admin-disclosure"><summary>Advanced analytics settings</summary><h3 className="operations-message">Analytics dashboard shortcut</h3><p className="operations-detail">This optional external link is separate from reporting credentials and does not enable tracking.</p>{error && <div><p role="alert">{error}</p>{!ready && <button className="admin-secondary-button" type="button" onClick={() => setAttempt(n => n + 1)}>Retry settings</button>}</div>}{loading ? <p role="status">Loading settings…</p> : <form className="operations-form" onSubmit={save}><label>Analytics source<select disabled={!manage || saving || !ready} value={settings.analytics_provider} onChange={e => setSettings(p => ({ ...p, analytics_provider: e.target.value, analytics_dashboard_url: e.target.value === 'none' ? '' : p.analytics_dashboard_url }))}><option value="none">Not configured</option><option value="google_analytics">Google Analytics</option><option value="plausible">Plausible</option><option value="other">Other</option></select></label><label>Analytics dashboard URL<input type="url" placeholder="https://" maxLength={1000} required={settings.analytics_provider !== 'none'} disabled={!manage || saving || !ready || settings.analytics_provider === 'none'} value={settings.analytics_dashboard_url} onChange={e => setSettings(p => ({ ...p, analytics_dashboard_url: e.target.value }))} /></label>{manage && <button className="admin-primary-button" disabled={saving || !ready}>{saving ? 'Saving…' : 'Save settings'}</button>}<p role="status">{settingsDraft.restored ? 'Unsaved settings restored. Review before saving.' : status}</p></form>}</details></div></AdminCard>
  </div>;
}
