import type { Express } from 'express';
import { z } from 'zod';
import type { Providers } from '../shared/providers.js';
import type { Authorization } from './auth.js';
import { HttpError, providerError } from '../shared/errors.js';
import { rows, one } from '../shared/data.js';
import { auditEvent } from '../shared/audit.js';

const optionalDate = z.iso.date().nullable();
const amount = z.string().regex(/^\d{1,9}(\.\d{1,2})?$/, 'Use a non-negative amount with at most two decimal places');
const safeUrl = z.string().max(1000).refine(value => { if (!value) return true; try { const url = new URL(value); return url.protocol === 'https:' && !url.username && !url.password; } catch { return false; } }, 'Use an HTTPS URL without credentials');
export const billingServiceInput = z.object({ name: z.string().trim().min(1).max(100), category: z.enum(['hosting', 'email', 'domain', 'workspace', 'other']), owner: z.string().trim().max(120), amount: amount.nullable(), currency: z.enum(['USD', 'KES', 'EUR', 'GBP']), cycle: z.enum(['monthly', 'quarterly', 'annual', 'one_time', 'usage_based']), next_due_date: optionalDate, portal_url: safeUrl, notes: z.string().trim().max(2000), active: z.boolean() }).strict();
export const paymentInput = z.object({ amount, currency: z.enum(['USD', 'KES', 'EUR', 'GBP']), paid_on: z.iso.date(), next_due_date: optionalDate, reference: z.string().trim().max(120), expected_updated_at: z.iso.datetime({ offset: true }), idempotency_key: z.uuid() }).strict().refine(value => !value.next_due_date || value.next_due_date > value.paid_on, { message: 'Next due date must be after payment date', path: ['next_due_date'] });
export const settingsInput = z.object({ analytics_provider: z.enum(['none', 'google_analytics', 'plausible', 'other']), analytics_dashboard_url: safeUrl }).strict().refine(value => value.analytics_provider === 'none' ? !value.analytics_dashboard_url : Boolean(value.analytics_dashboard_url), { message: 'Choose a provider and its HTTPS dashboard URL together', path: ['analytics_dashboard_url'] });
function check(error: { code?: string; message?: string } | null) { if (error && ['42P01', 'PGRST205', 'PGRST202'].includes(error.code || '')) throw new HttpError(503, 'Operations storage is not configured. Ask the owner to review the manual billing migration.'); providerError(error); }
export function registerOperations(app: Express, p: Providers, a: Authorization) {
    async function reader(req: Parameters<Authorization['user']>[0]) { const u = await a.user(req); if (u.role !== 'super_admin' && !(await a.permissions(u)).includes('donations.view')) throw new HttpError(403, 'Billing access required'); return u; }
    app.get('/api/admin/billing', async (req, res) => { await reader(req); const r = await p.db.from('service_billing').select('*').order('next_due_date', { ascending: true, nullsFirst: false }).limit(500); check(r.error); res.json({ results: rows(r) }); });
    app.post('/api/admin/billing', async (req, res) => { const u = await a.require(req, undefined, 'super_admin'); const body = billingServiceInput.parse(req.body); const r = await p.db.from('service_billing').insert({ ...body, created_by: u.id }).select('*'); check(r.error); const service = one(r, 'Service not found'); await auditEvent(p, { action: 'BILLING_SERVICE_CREATED', entity_type: 'service_billing', entity_id: service.id, actor_user_id: u.id, after_state: body, request_id: res.locals.requestId, reason: 'Service added to billing register' }); res.status(201).json(service); });
    app.patch('/api/admin/billing/:id', async (req, res) => { const u = await a.require(req, undefined, 'super_admin'); const id = z.uuid().parse(req.params.id); const { expected_updated_at, ...body } = billingServiceInput.extend({ expected_updated_at: z.iso.datetime({ offset: true }) }).parse(req.body); const r = await p.db.from('service_billing').update({ ...body, updated_at: new Date().toISOString() }).eq('id', id).eq('updated_at', expected_updated_at).select('*'); check(r.error); if (!r.data?.length) throw new HttpError(409, 'Service changed or is unavailable. Reload before saving.'); const service = one(r, 'Service not found'); await auditEvent(p, { action: 'BILLING_SERVICE_UPDATED', entity_type: 'service_billing', entity_id: id, actor_user_id: u.id, after_state: body, request_id: res.locals.requestId, reason: 'Billing service details updated' }); res.json(service); });
    app.get('/api/admin/billing/:id/payments', async (req, res) => { await reader(req); const id = z.uuid().parse(req.params.id); const r = await p.db.from('service_billing_payments').select('id,service_id,amount,currency,paid_on,reference,created_at').eq('service_id', id).order('paid_on', { ascending: false }).limit(100); check(r.error); res.json({ results: rows(r) }); });
    app.post('/api/admin/billing/:id/payments', async (req, res) => { const u = await a.require(req, undefined, 'super_admin'); const id = z.uuid().parse(req.params.id); const b = paymentInput.parse(req.body); const r = await p.db.rpc('ltc_record_service_payment', { service_uuid: id, actor_uuid: u.id, paid_amount: b.amount, paid_currency: b.currency, payment_date: b.paid_on, following_due_date: b.next_due_date, payment_reference: b.reference, expected_version: b.expected_updated_at, submission_key: b.idempotency_key, event_request_id: res.locals.requestId }); if (r.error?.code === '42501') throw new HttpError(403, 'Super admin access required'); if (r.error?.code === '22023') throw new HttpError(422, 'Payment details do not match the service or deadline.'); if (['40001', '23505'].includes(r.error?.code || '')) throw new HttpError(409, 'Service changed. Reload before recording payment.'); check(r.error); res.status(201).json(r.data); });
    app.get('/api/admin/operations-settings', async (req, res) => { await a.user(req); const r = await p.db.from('operations_settings').select('analytics_provider,analytics_dashboard_url').eq('id', true).limit(1); check(r.error); res.json(rows(r)[0] || { analytics_provider: 'none', analytics_dashboard_url: '' }); });
    app.put('/api/admin/operations-settings', async (req, res) => { const u = await a.require(req, undefined, 'super_admin'); const b = settingsInput.parse(req.body); const r = await p.db.from('operations_settings').upsert({ id: true, ...b, updated_at: new Date().toISOString() }).select('analytics_provider,analytics_dashboard_url'); check(r.error); await auditEvent(p, { action: 'OPERATIONS_SETTINGS_UPDATED', entity_type: 'operations_settings', entity_id: 'analytics', actor_user_id: u.id, after_state: b, request_id: res.locals.requestId, reason: 'Analytics dashboard configuration updated' }); res.json(rows(r)[0]); });
}
