import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequestCoordinator } from '../src/shared/api/requestCoordinator.js';
function setup(fetcher) {
 let access='old',refresh='refresh',version=0;let logout=0;
 const storage={getAccessToken:()=>access,getRefreshToken:()=>refresh,getVersion:()=>version,setTokens:t=>{access=t.access;refresh=t.refresh;version++;},clear:()=>{access=null;refresh=null;version++;}};
 const client=createRequestCoordinator({baseUrl:'http://fixture.invalid',refreshPath:'/refresh',storage,fetcher,onLogout:()=>logout++,normalizeError:async r=>Object.assign(new Error('API failure'),{status:r.status})});
 return {client,storage,logout:()=>logout};
}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('concurrent 401s share refresh and each replay once',async()=>{let refreshes=0;const s=setup(async(url,init)=>{if(url.endsWith('/refresh')){refreshes++;await new Promise(r=>setTimeout(r,10));return json({access:'new',refresh:'rotated'});}return init.headers.get('Authorization')==='Bearer new'?json({ok:true}):json({},401);});const r=await Promise.all([s.client.request('/a',{auth:true}),s.client.request('/b',{auth:true}),s.client.refresh()]);assert.equal(refreshes,1);assert.equal(s.logout(),0);assert.deepEqual(r.slice(0,2),[{ok:true},{ok:true}]);});
test('provider outage preserves session',async()=>{const s=setup(async()=>json({},503));await assert.rejects(s.client.refresh(),{status:503});assert.equal(s.storage.getAccessToken(),'old');assert.equal(s.logout(),0);});
test('invalid refresh logs out once',async()=>{const s=setup(async()=>json({},401));await Promise.all([s.client.refresh(),s.client.refresh()]);assert.equal(s.storage.getAccessToken(),null);assert.equal(s.logout(),1);});
test('logout while refreshing cannot restore tokens',async()=>{let resolve;const s=setup(()=>new Promise(r=>{resolve=r;}));const work=s.client.refresh();s.storage.clear();resolve(json({access:'new',refresh:'new'}));await work;assert.equal(s.storage.getAccessToken(),null);});
test('old GET cannot repopulate cache after mutation',async()=>{let complete;let value=1;let calls=0;const s=setup(async(_url,init)=>{if(init.method==='PATCH'){value=2;return json({ok:true});}calls++;if(calls===1)return new Promise(r=>{complete=()=>r(json({value:1}));});return json({value});});const old=s.client.request('/item');await s.client.request('/item',{method:'PATCH',body:'{}'});complete();await old;assert.deepEqual(await s.client.request('/item'),{value:2});assert.equal(calls,2);});
test('cache cannot cross sessions',async()=>{let calls=0;const s=setup(async()=>json({calls:++calls}));await s.client.request('/private',{auth:true});s.storage.setTokens({access:'another',refresh:'another'});assert.deepEqual(await s.client.request('/private',{auth:true}),{calls:2});});
test('deadline aborts and mutations are not retried',async()=>{let calls=0;const s=setup((_url,init)=>{calls++;return new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(init.signal.reason),{once:true}));});await assert.rejects(s.client.request('/payment',{method:'POST',body:'{}',timeoutMs:10}),{name:'TimeoutError'});assert.equal(calls,1);});
test('cancelled consumer does not cancel another read',async()=>{const s=setup(async(_url,init)=>{await new Promise((resolve,reject)=>{const t=setTimeout(resolve,20);init.signal.addEventListener('abort',()=>{clearTimeout(t);reject(init.signal.reason);},{once:true});});return json({ok:true});});const controller=new AbortController();const cancelled=s.client.request('/read',{signal:controller.signal});const other=s.client.request('/read');controller.abort();await assert.rejects(cancelled);assert.deepEqual(await other,{ok:true});});
