import { useUnsavedChanges } from '../components/useUnsavedChanges';
import { useEffect, useRef, useState } from 'react';
import Cropper from 'react-easy-crop';
import { Check, FlipHorizontal2, ImagePlus, RotateCcw, RotateCw, Trash2, X } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { AdminBadge, AdminCard, AdminEmptyState, AdminModal, ConfirmDialog, PageHeader } from '../components/AdminPrimitives';
import { teamProfilesService } from '../../services/teamProfiles/teamProfiles.service';
import { PROFILE_DEPARTMENTS } from '../../constants/departments';
import getCroppedImg from '../../utils/cropUtils';
import { validatePortrait, validateProfile } from './profileValidation';
import { useAuth } from '../../app/providers/AuthProvider';

const labels = { pending_review: 'Pending review', published: 'Published', changes_requested: 'Changes requested', approved: 'Approved', rejected: 'Rejected', draft: 'Draft' };
const tone = (s) => s === 'published' ? 'success' : s === 'pending_review' ? 'warning' : s === 'rejected' ? 'danger' : '';
const cleanEditor = { crop: { x: 0, y: 0 }, zoom: 1, turn: 0, straighten: 0, flip: false, pixels: null };

export default function ProfileReviewPage() {
  const { can, user } = useAuth();
  const { profileId } = useParams(); const navigate = useNavigate(); const objectUrl = useRef('');
  const [profile, setProfile] = useState(null); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null); const [note, setNote] = useState(''); const [errors, setErrors] = useState({});
  const [busy, setBusy] = useState(false); const [alert, setAlert] = useState(''); const [editorImage, setEditorImage] = useState(''); const [editor, setEditor] = useState(cleanEditor);
  const profileDirty = modal === 'edit' && JSON.stringify(form) !== JSON.stringify(profile);
  const profileDraft = useUnsavedChanges({ key: `${user?.id}:profile-review:${profileId}`, dirty: profileDirty, draft: form, restore: setForm, ready: modal === 'edit' && Boolean(profile) });
  const closeEdit = () => { if (!busy && (!profileDirty || window.confirm('Discard unsaved profile changes?'))) { profileDraft.discard(); setForm(profile); setModal(null); } };
  const rotation = editor.turn + editor.straighten;
  const editEditor = (next) => setEditor((current) => ({ ...current, ...next }));

  useEffect(() => { setLoading(true); teamProfilesService.getById(profileId).then((item) => { setProfile(item); setForm(item); }).catch(() => setProfile(null)).finally(() => setLoading(false)); }, [profileId]);
  useEffect(() => () => { if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); }, []);

  const closeEditor = () => { if (busy) return; if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); objectUrl.current = ''; setEditorImage(''); setEditor(cleanEditor); setAlert(''); setModal(null); };
  const openEditor = () => { setEditor(cleanEditor); setEditorImage(profile.image?.previewUrl || ''); setAlert(''); setModal('portrait'); };
  const chooseImage = (event) => { const file = event.target.files?.[0]; if (!file) return; const error = validatePortrait(file); if (error) { setAlert(error); return; } if (objectUrl.current) URL.revokeObjectURL(objectUrl.current); objectUrl.current = URL.createObjectURL(file); setEditorImage(objectUrl.current); setEditor(cleanEditor); setAlert(''); event.target.value = ''; };
  const savePortrait = async () => { if (!editorImage || !editor.pixels) return; setBusy(true); setAlert(''); try { const blob = await getCroppedImg(editorImage, editor.pixels, { rotation, flipHorizontal: editor.flip }); const image = { file: new File([blob], `profile-${profile.id}.jpg`, { type: 'image/jpeg' }) }; const saved = await teamProfilesService.update(profile.id, { ...profile, image }); setProfile(saved); setForm(saved); setBusy(false); closeEditor(); } catch (error) { setAlert(error?.message || 'Could not save this image. Select the original photo and try again.'); setBusy(false); } };
  const save = async (event) => { event.preventDefault(); const next = validateProfile(form, { requireImage: false }); setErrors(next); if (Object.keys(next).length) return; setBusy(true); try { const saved = await teamProfilesService.update(profile.id, form); profileDraft.discard(); setProfile(saved); setForm(saved); setModal(null); } finally { setBusy(false); } };
  const action = async (type) => { setBusy(true); setAlert(''); try { if (type === 'approve') setProfile(await teamProfilesService.publish(profile.id)); if (type === 'changes') setProfile(await teamProfilesService.requestChanges(profile.id, note)); if (type === 'reject') setProfile(await teamProfilesService.reject(profile.id, note)); if (type === 'unpublish') setProfile(await teamProfilesService.unpublish(profile.id)); setModal(null); setNote(''); } catch (error) { setAlert(error?.message || 'The action could not be completed.'); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await teamProfilesService.delete(profile.id); navigate('/admin/profiles', { replace: true }); } catch (error) { setAlert(error?.message || 'The profile could not be deleted.'); setModal(null); setBusy(false); } };

  if (loading) return <div className="admin-page"><div className="admin-state">Loading profile…</div></div>;
  if (!profile) return <div className="admin-page"><AdminCard><AdminEmptyState title="Profile not found" description="This profile may have been removed." action={<Link className="admin-secondary-button" to="/admin/profiles">Back to profiles</Link>} /></AdminCard></div>;
  const initials = profile.name.split(' ').map((part) => part[0]).join('').slice(0, 2);
  return <div className="admin-page">
    <Link className="admin-back-link" to="/admin/profiles">Team Profiles</Link><PageHeader title={profile.name} subtitle={profile.email} action={<AdminBadge tone={tone(profile.status)}>{labels[profile.status]}</AdminBadge>} />
    {alert && modal !== 'portrait' && <p className="profile-review-alert" role="alert">{alert}</p>}
    <div className="profile-review-grid"><AdminCard><div className="admin-card__body"><div className="profile-review-image">{profile.image?.previewUrl ? <img src={profile.image.previewUrl} alt={`${profile.name} portrait`} loading="lazy" /> : <span>{initials}</span>}</div>{can('profiles.update') && <button className="admin-secondary-button profile-edit-portrait" type="button" onClick={openEditor}><ImagePlus size={15} /> Edit portrait</button>}<h2 className="profile-review-name">{profile.name}</h2><p className="profile-review-role">{profile.role} · {profile.department}</p><blockquote className="profile-review-quote">“{profile.quote}”</blockquote><p className="profile-review-bio">{profile.bio}</p><div className="profile-review-file"><strong>Portrait file</strong><span>{profile.image?.fileName || 'Current profile portrait'}</span></div></div></AdminCard>
    <AdminCard><div className="admin-card__body"><div className="profile-review-details"><h2>Submission details</h2><dl className="user-detail-list">{[['Name',profile.name],['Email',profile.email],['Role',profile.role],['Department',profile.department],['Submitted',profile.submittedAt ? new Date(profile.submittedAt).toLocaleString() : 'Not submitted'],['Reviewed by',profile.reviewedBy || '—']].map(([key,value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{profile.reviewNote && <div className="profile-review-note"><strong>Review note</strong><p>{profile.reviewNote}</p></div>}</div><div className="profile-review-actions"><button className="admin-secondary-button" type="button" onClick={() => setModal('edit')}>Edit profile</button>{profile.status === 'pending_review' && <><button className="admin-primary-button" type="button" onClick={() => setModal('approve')}><Check size={14} /> Approve & publish</button><button className="admin-secondary-button" type="button" onClick={() => setModal('changes')}>Request changes</button><button className="admin-secondary-button admin-danger-outline" type="button" onClick={() => setModal('reject')}><X size={14} /> Reject</button></>}{profile.status === 'published' && <button className="admin-secondary-button admin-danger-outline" type="button" onClick={() => setModal('unpublish')}>Unpublish profile</button>}<button className="admin-secondary-button admin-danger-outline" type="button" onClick={() => setModal('delete')}><Trash2 size={14} /> Delete profile</button></div></div></AdminCard></div>
    {['approve','unpublish','delete'].map((type) => <ConfirmDialog key={type} open={modal === type} title={type === 'approve' ? 'Approve profile?' : type === 'delete' ? 'Delete profile permanently?' : 'Unpublish profile?'} description={type === 'delete' ? `${profile.name}'s profile and stored portrait will be permanently removed. This cannot be undone.` : type === 'approve' ? `${profile.name}'s information and portrait will be published.` : 'The profile will be removed from public visibility but remain saved.'} confirmLabel={type === 'delete' ? 'Delete profile' : type === 'approve' ? 'Approve & publish' : 'Unpublish'} variant={type === 'approve' ? 'primary' : 'danger'} loading={busy} onClose={() => setModal(null)} onConfirm={type === 'delete' ? remove : () => action(type)} />)}
    <AdminModal open={modal === 'portrait'} title="Edit portrait" description="Crop, zoom, straighten, rotate, or flip the image." onClose={closeEditor} actions={<><button className="admin-secondary-button" disabled={busy} type="button" onClick={closeEditor}>Cancel</button><button className="admin-primary-button" disabled={busy || !editor.pixels} type="button" onClick={savePortrait}>{busy ? 'Saving…' : 'Save portrait'}</button></>}><label className="admin-secondary-button portrait-file-button"><ImagePlus size={15} /> {editorImage ? 'Choose another photo' : 'Choose a photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} /></label>{editorImage ? <><div className="portrait-crop-area"><Cropper image={editorImage} crop={editor.crop} zoom={editor.zoom} rotation={rotation} aspect={1} transform={`translate(${editor.crop.x}px, ${editor.crop.y}px) rotate(${rotation}deg) scale(${editor.flip ? -editor.zoom : editor.zoom}, ${editor.zoom})`} onCropChange={(crop) => editEditor({ crop })} onZoomChange={(zoom) => editEditor({ zoom })} onCropComplete={(_, pixels) => editEditor({ pixels })} /></div><div className="portrait-editor-controls"><label>Zoom <span>{editor.zoom.toFixed(1)}×</span><input type="range" min="1" max="3" step="0.1" value={editor.zoom} onChange={(e) => editEditor({ zoom: Number(e.target.value) })} /></label><label>Straighten <span>{editor.straighten}°</span><input type="range" min="-15" max="15" step="0.5" value={editor.straighten} onChange={(e) => editEditor({ straighten: Number(e.target.value) })} /></label><div className="portrait-editor-toolbar"><button type="button" onClick={() => editEditor({ turn: editor.turn - 90 })}><RotateCcw size={15} /> Left</button><button type="button" onClick={() => editEditor({ turn: editor.turn + 90 })}><RotateCw size={15} /> Right</button><button type="button" className={editor.flip ? 'active' : ''} onClick={() => editEditor({ flip: !editor.flip })}><FlipHorizontal2 size={15} /> Flip</button><button type="button" onClick={() => setEditor(cleanEditor)}>Reset</button></div></div></> : <p className="portrait-editor-empty">Choose a JPEG, PNG, or WebP portrait under 5 MB.</p>}{alert && <p className="admin-form-error portrait-editor-error" role="alert">{alert}</p>}</AdminModal>
    <AdminModal open={modal === 'changes' || modal === 'reject'} title={modal === 'changes' ? 'Request changes' : 'Reject submission'} onClose={() => setModal(null)} actions={<><button className="admin-secondary-button" type="button" onClick={() => setModal(null)}>Cancel</button><button className="admin-primary-button" disabled={!note.trim() || busy} type="button" onClick={() => action(modal)}>{busy ? 'Saving…' : 'Confirm'}</button></>}><div className="admin-form-field"><label htmlFor="review-note">Reason</label><textarea id="review-note" value={note} onChange={(e) => setNote(e.target.value)} /></div></AdminModal>
    <AdminModal guardChanges={false} open={modal === 'edit'} title="Edit profile" onClose={closeEdit} actions={<><button className="admin-secondary-button" type="button" onClick={closeEdit}>Cancel</button><button className="admin-primary-button" type="submit" form="review-edit-form" disabled={busy}>Save changes</button></>}><form id="review-edit-form" onSubmit={save}>{profileDraft.restored && <p role="status">Unsaved profile draft restored. Review before saving.</p>}{['name','email','role'].map((key) => <div className="admin-form-field" key={key}><label htmlFor={`review-${key}`}>{key}</label><input id={`review-${key}`} type={key === 'email' ? 'email' : 'text'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /></div>)}<div className="admin-form-field"><label htmlFor="review-department">Department</label><select id="review-department" value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })}>{PROFILE_DEPARTMENTS.map((item) => <option key={item}>{item}</option>)}</select></div>{['quote','bio'].map((key) => <div className="admin-form-field" key={key}><label htmlFor={`review-${key}`}>{key}</label>{key === 'bio' ? <textarea id={`review-${key}`} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /> : <input id={`review-${key}`} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />}</div>)}{Object.keys(errors).length > 0 && <p className="admin-form-error">Please correct the highlighted profile details.</p>}</form></AdminModal>
  </div>;
}
